name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          # Note that we assume the following things about the ecosystem tests here:
          #   1. Every directory in `build_test` is a project managed with yarn
          #   2. All these projects store their cache in `<project>/.yarn/cache`
          # It's not that robust, but should be sufficient for us for now.
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/ecosystem-tests/*/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        id: dev-package-uploader-cache
        with:
          path:
            '${{ github.workspace }}/scripts/dev-package-uploader/node_modules'
          key:
            ${{ runner.os }}-dev-package-uploader-cache-${{
            hashFiles('scripts/dev-package-uploader/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dev-package-uploader-cache-

      - run: yarn install
      - run: yarn typecheck
      - run: yarn lint:all --max-warnings 0
      - run: yarn test
      - run: yarn build
      - run: yarn test:ecosystem
      - name: Download playwright
        run: yarn workspace playground run playwright install
      - name: Run e2e tests with percy
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: 'yarn test:e2e:ci'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Install dependencies of the dev-package-uploader
        working-directory: ${{ github.workspace }}/scripts/dev-package-uploader
        run: npm install
      - name: Build the theatre packages
        run: yarn build
      - name: Publish the packages
        env:
          DO_REGION: 'nyc3'
          DO_BUCKET: 'theatrejs-packages'
          DO_SECRET: ${{ secrets.DO_SPACES_SECRET }}
          DO_API_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_DOMAIN: ''
          LATEST_COMMIT_HASH: ${{ github.sha }}
          FOLDER: '@theatre'
        run: npx zx scripts/generate-development-package-tarballs.mjs
